### ISSUE TITLE
Update indents

### ISSUE THREAD

**Issue by FiodarHmyza** [LedakovichIvan/1-syntax#16]
https://github.com/LedakovichIvan/1-syntax/blob/32e70e6fe49b08ffe2eb8915a6ad0409380cfbc6/src/ArgumentsParser.java#L22

https://github.com/LedakovichIvan/1-syntax/blob/32e70e6fe49b08ffe2eb8915a6ad0409380cfbc6/src/Help.java#L4C1-L4C35
https://github.com/LedakovichIvan/1-syntax/blob/32e70e6fe49b08ffe2eb8915a6ad0409380cfbc6/src/Help.java#L3
https://github.com/LedakovichIvan/1-syntax/blob/32e70e6fe49b08ffe2eb8915a6ad0409380cfbc6/src/Parameters.java#L9
And so on. There are a lot of places in code with absent space.

**Comment by IvanLedakovich** [comment]
As far as I've heard Prettier is available in the Ultimate edition of IDEA. What do you use personally / can recommend?
